#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BYTES_PER_LINE = 16


def symbol_for(relative: str) -> str:
    return "g_sumoAsset_" + re.sub(r"[^A-Za-z0-9]", "_", relative)


def blob_source(relative: str, payload: bytes) -> str:
    symbol = symbol_for(relative)
    out = [
        f"// Generated by cmake/embed_assets.py from assets/{relative}."
        "  Do not edit.\n",
        "\n",
        f"extern const unsigned char {symbol}[];\n",
        f"extern const unsigned long {symbol}_size;\n",
        "\n",
        f"const unsigned char {symbol}[] = {{\n",
    ]
    for start in range(0, len(payload), BYTES_PER_LINE):
        chunk = payload[start:start + BYTES_PER_LINE]
        out.append("    " + "".join(f"0x{byte:02x}," for byte in chunk) + "\n")
    out.append("};\n")
    out.append(f"const unsigned long {symbol}_size = {len(payload)}ul;\n")
    return "".join(out)


def index_source(entries: list[str]) -> str:
    out = [
        "// Generated by cmake/embed_assets.py.  Do not edit.\n",
        "\n",
        '#include "sumo_portable.h"\n',
        "\n",
    ]
    for relative in entries:
        symbol = symbol_for(relative)
        out.append(f"extern const unsigned char {symbol}[];\n")
        out.append(f"extern const unsigned long {symbol}_size;\n")
    out.append("\n")
    out.append("namespace {\n")
    out.append("struct SumoEmbeddedAsset {\n")
    out.append("  const char *name;\n")
    out.append("  const unsigned char *data;\n")
    out.append("  unsigned long size;\n")
    out.append("};\n")
    out.append("\n")
    out.append("const SumoEmbeddedAsset c_embeddedAssets[] = {\n")
    for relative in entries:
        symbol = symbol_for(relative)
        out.append(f'    {{"{relative}", {symbol}, {symbol}_size}},\n')
    out.append("};\n")
    out.append("\n")
    out.append("bool SameName(const char *left, const char *right) {\n")
    out.append("  while (*left != 0 && *left == *right) {\n")
    out.append("    ++left;\n")
    out.append("    ++right;\n")
    out.append("  }\n")
    out.append("  return *left == 0 && *right == 0;\n")
    out.append("}\n")
    out.append("} // namespace\n")
    out.append("\n")
    out.append("SumoS32 SumoLookupEmbeddedAsset(const char *name,\n")
    out.append("                                const void **data,\n")
    out.append("                                SumoU32 *size) {\n")
    out.append("  if (name == 0)\n")
    out.append("    return 0;\n")
    out.append("  for (SumoU32 index = 0;\n")
    out.append("       index < sizeof(c_embeddedAssets) / "
               "sizeof(c_embeddedAssets[0]); ++index) {\n")
    out.append("    if (!SameName(name, c_embeddedAssets[index].name))\n")
    out.append("      continue;\n")
    out.append("    if (data != 0)\n")
    out.append("      *data = c_embeddedAssets[index].data;\n")
    out.append("    if (size != 0)\n")
    out.append("      *size = (SumoU32)c_embeddedAssets[index].size;\n")
    out.append("    return 1;\n")
    out.append("  }\n")
    out.append("  return 0;\n")
    out.append("}\n")
    return "".join(out)


def output_name(relative: str) -> str:
    return "embedded_" + re.sub(r"[^A-Za-z0-9]", "_", relative) + ".cpp"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--list", action="store_true",
                        help="print the generated file names and exit")
    parser.add_argument("assets", nargs="+")
    arguments = parser.parse_args()

    relatives = list(arguments.assets)

    symbols: dict[str, str] = {}
    for relative in relatives:
        symbol = symbol_for(relative)
        if symbol in symbols:
            raise SystemExit(
                f"embed_assets.py: {relative} and {symbols[symbol]} both map to "
                f"the identifier {symbol}; rename one"
            )
        symbols[symbol] = relative

    names = [output_name(relative) for relative in relatives]
    names.append("embedded_index.cpp")

    if arguments.list:
        for name in names:
            print(arguments.output_dir / name)
        return 0

    arguments.output_dir.mkdir(parents=True, exist_ok=True)
    for relative in relatives:
        source = arguments.root / relative
        if not source.is_file():
            raise SystemExit(f"embed_assets.py: missing asset {source}")
        target = arguments.output_dir / output_name(relative)
        text = blob_source(relative, source.read_bytes())
        if not target.exists() or target.read_text(encoding="ascii") != text:
            target.write_text(text, encoding="ascii")

    index = arguments.output_dir / "embedded_index.cpp"
    text = index_source(relatives)
    if not index.exists() or index.read_text(encoding="ascii") != text:
        index.write_text(text, encoding="ascii")
    return 0


if __name__ == "__main__":
    sys.exit(main())
