set(SUMO_SOURCES
  SUMO/sumo.rc
  SUMO/core/assert.cpp
  SUMO/core/assert.h
  SUMO/core/big_integer.cpp
  SUMO/core/big_integer_add_subtract.asm
  SUMO/core/big_integer_construct.cpp
  SUMO/core/big_integer_arithmetic.cpp
  SUMO/core/big_integer_compare.cpp
  SUMO/core/big_integer_divide.cpp
  SUMO/core/big_integer.h
  SUMO/core/big_integer_assign.cpp
  SUMO/core/big_integer_log.asm
  SUMO/core/big_integer_modular_power.cpp
  SUMO/core/big_integer_multiply.asm
  SUMO/core/big_integer_multiply.cpp
  SUMO/core/big_integer_power.asm
  SUMO/core/big_integer_shift.asm
  SUMO/core/big_integer_shift.cpp
  SUMO/core/big_integer_string.cpp
  SUMO/core/big_integer_write_string.asm
  SUMO/core/retail_literals.asm
  SUMO/core/containers.h
  SUMO/platform/assembly_functions.h
  SUMO/library_dxsdk.h
  SUMO/library_msvc.h
  SUMO/library_windows.h
  SUMO/platform/main.cpp
  SUMO/core/decomp.h
  SUMO/parser/expression_parser.cpp
  SUMO/parser/expression_parser_turn_to.cpp
  SUMO/parser/expression_parser_identifier.asm
  SUMO/parser/expression_parser_find_cursor.cpp
  SUMO/parser/expression_parser_prepare.asm
  SUMO/parser/expression_parser_compile_expression.asm
  SUMO/parser/expression_parser_compile_value.asm
  SUMO/parser/expression_parser_compile_statement.asm
  SUMO/parser/expression_parser_compile_helpers.cpp
  SUMO/parser/expression_parser_compile_operation.cpp
  SUMO/parser/expression_parser_compile_function.cpp
  SUMO/parser/expression_parser_compile_block.cpp
  SUMO/parser/expression_parser_eval.asm
  SUMO/parser/expression_parser_dump.cpp
  SUMO/parser/expression_parser.h
  "${SUMO_AUDIO_DATA_ASM}"
  "${SUMO_AUDIO_XM_PARSER}"
  SUMO/audio/game_audio.cpp
  SUMO/audio/game_audio_bss.asm
  SUMO/audio/game_sound_bss.asm
  SUMO/render/game_texture_distort_layers.asm
  SUMO/audio/game_audio_channel_reset.cpp
  SUMO/audio/game_audio_channel_reset.asm
  SUMO/audio/game_audio_volume_column.cpp
  SUMO/audio/game_audio_assets.cpp
  SUMO/audio/game_audio_decode_assets.asm
  SUMO/audio/game_sound_slot.h
  SUMO/audio/game_audio_play_sound.cpp
  SUMO/audio/game_audio_mixer.asm
  SUMO/render/game_texture_assets.cpp
  SUMO/render/game_texture_hsv_rgb.asm
  SUMO/render/game_texture_program.asm
  SUMO/render/game_render_normalmap.asm
  SUMO/render/game_render_ramps.cpp
  SUMO/render/game_render_text.cpp
  SUMO/render/game_texture_handles.asm
  SUMO/render/game_render_texture_init.asm
  SUMO/render/game_render_projection.asm
  SUMO/render/game_render_projection.cpp
  SUMO/render/game_render_scratch.cpp
  SUMO/render/game_render_water.asm
  SUMO/physics/game_box_render_storage.asm
  SUMO/physics/game_box_contacts_wrapper.cpp
  SUMO/render/game_render_display_modes.asm
  SUMO/render/game_render_device_init.cpp
  SUMO/render/game_render_screenshot.asm
  SUMO/render/game_texture_hsv.cpp
  SUMO/physics/game_box_edges.cpp
  SUMO/physics/game_box_face.cpp
  SUMO/physics/game_box_geometry.cpp
  SUMO/physics/game_box_initialize.cpp
  SUMO/physics/game_box_integrate.cpp
  SUMO/physics/game_box_projectile.cpp
  SUMO/physics/game_box_impulse.cpp
  SUMO/physics/game_box_mass.cpp
  SUMO/physics/game_box_mass_accumulator.cpp
  SUMO/physics/game_box_joint_align.asm
  SUMO/physics/game_box_mass_triangle.asm
  SUMO/physics/game_box_point.cpp
  SUMO/physics/game_box_pool.cpp
  SUMO/physics/game_box_render_state.cpp
  SUMO/physics/game_box_render.asm
  SUMO/physics/game_box_lifecycle.cpp
  SUMO/physics/game_box_paired_impulse.cpp
  SUMO/physics/game_box_water_state.cpp
  SUMO/physics/game_box_water.asm
  SUMO/physics/game_box_water_loop.asm
  SUMO/game/game_replay.h
  SUMO/game/game_replay.cpp
  SUMO/game/game_replay.asm
  SUMO/game/game_replay_globals.cpp
  SUMO/physics/game_water_field.cpp
  SUMO/physics/game_water_update.asm
  SUMO/render/game_wavy_text_transform.cpp
  SUMO/render/game_wavy_text_transform.asm
  SUMO/game/game_man_pose.cpp
  SUMO/game/game_man_bss.asm
  SUMO/game/game_man_initialize.asm
  SUMO/game/game_man_cross_marker.cpp
  SUMO/game/game_man_cross_marker.asm
  SUMO/game/game_man_find_opponent.cpp
  SUMO/game/game_man_ai.asm
  SUMO/game/game_man_update.asm
  SUMO/game/game_man_pose_controller.asm
  SUMO/physics/game_collision_heap.asm
  SUMO/physics/game_collision_clip.asm
  SUMO/physics/game_collision_state.cpp
  SUMO/physics/game_collision_bss.asm
  SUMO/physics/game_box_bss.asm
  SUMO/physics/game_box_triangle_order.asm
  SUMO/physics/game_random_global.cpp
  SUMO/physics/game_box_fracture.asm
  SUMO/physics/game_collision_solver.asm
  SUMO/physics/game_collision_contacts.asm
  SUMO/game/game_data.cpp
  SUMO/game/game_man_helpers.cpp
  SUMO/game/game_man_energy.asm
  SUMO/game/game_man_momentum.asm
  SUMO/game/game_man_limb_angle.cpp
  SUMO/game/game_man_input.cpp
  SUMO/game/game_man_render.cpp
  SUMO/platform/game_platform.cpp
  SUMO/platform/game_window_proc.asm
  SUMO/game/game_runtime.cpp
  SUMO/game/game_runtime.asm
  SUMO/game/game_default_arena.asm
  SUMO/game/game_hidden_screen.asm
  SUMO/physics/game_random_next.cpp
  SUMO/game/game_main_loop.cpp
  SUMO/game/game_main_loop_exact.asm
  SUMO/game/game_level_editor.cpp
  SUMO/game/game_level_load.cpp
  SUMO/game/game_level_load_data.asm
  SUMO/render/game_mouse_ray.cpp
  SUMO/game/game_runtime.h
  SUMO/render/game_render.cpp
  SUMO/render/game_render_bss.asm
  SUMO/game/game_scene.cpp
  SUMO/render/game_camera.asm
  SUMO/game/game_settings.cpp
  SUMO/game/game_settings_transform.asm
  SUMO/game/game_settings_load.cpp
  SUMO/core/matrix3_add.cpp
  SUMO/core/matrix3_inverse_multiply.cpp
  SUMO/core/matrix3_inverse.asm
  SUMO/core/matrix3_orthonormalize.asm
  SUMO/core/matrix3_rotation.cpp
  SUMO/parser/parser_helpers.h
  SUMO/parser/parser_containers.h
  SUMO/core/types.h
  SUMO/core/u32vector_ops.cpp
  SUMO/core/vector3.cpp
  SUMO/core/vector3_rotation.cpp
)
