include_guard(GLOBAL)

include(FetchContent)

if(POLICY CMP0219)
  set(CMAKE_POLICY_DEFAULT_CMP0219 NEW)
endif()

set(FETCHCONTENT_UPDATES_DISCONNECTED ON CACHE BOOL
  "Do not update pinned portable dependencies after their first fetch")

set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
set(SDL_ASSEMBLY OFF CACHE BOOL "" FORCE)

if(SUMO_SDL_VERSION STREQUAL "3")
  set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
  set(SDL_UNINSTALL OFF CACHE BOOL "" FORCE)
  set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
  set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)

  FetchContent_Declare(sumo_sdl_source
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG 147a8ee32dbf9ac02f3794964490687b6bbda1bc
    GIT_SHALLOW FALSE
    GIT_PROGRESS TRUE
  )
else()
  set(SDL_TEST OFF CACHE BOOL "" FORCE)
  set(SDL2_DISABLE_INSTALL ON CACHE BOOL "" FORCE)
  set(SDL2_DISABLE_UNINSTALL ON CACHE BOOL "" FORCE)

  FetchContent_Declare(sumo_sdl_source
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG 5d249570393f7a37e037abf22cd6012a4cc56a71
    GIT_SHALLOW FALSE
    GIT_PROGRESS TRUE
  )
endif()

FetchContent_MakeAvailable(sumo_sdl_source)

add_library(sumo_sdl INTERFACE)
add_library(Sumo::SDL ALIAS sumo_sdl)
target_compile_definitions(sumo_sdl INTERFACE
  SUMO_SDL_VERSION=${SUMO_SDL_VERSION})

if(SUMO_SDL_VERSION STREQUAL "3")
  if(TARGET SDL3::SDL3-static)
    target_link_libraries(sumo_sdl INTERFACE SDL3::SDL3-static)
  elseif(TARGET SDL3::SDL3)
    target_link_libraries(sumo_sdl INTERFACE SDL3::SDL3)
  else()
    message(FATAL_ERROR "The pinned SDL3 source did not provide an SDL3 target")
  endif()
else()
  if(TARGET SDL2::SDL2-static)
    target_link_libraries(sumo_sdl INTERFACE SDL2::SDL2-static)
  elseif(TARGET SDL2::SDL2)
    target_link_libraries(sumo_sdl INTERFACE SDL2::SDL2)
  else()
    message(FATAL_ERROR "The pinned SDL2 source did not provide an SDL2 target")
  endif()
endif()

FetchContent_Declare(sumo_imgui_source
  GIT_REPOSITORY https://github.com/ocornut/imgui.git
  GIT_TAG f1cc2ae15e53a861a874c3034aae6798fde194ab
  GIT_SHALLOW FALSE
  GIT_PROGRESS TRUE
)
FetchContent_MakeAvailable(sumo_imgui_source)

if(SUMO_SDL_VERSION STREQUAL "3")
  set(SUMO_IMGUI_SDL_BACKEND imgui_impl_sdl3.cpp)
else()
  set(SUMO_IMGUI_SDL_BACKEND imgui_impl_sdl2.cpp)
endif()

add_library(sumo_imgui STATIC
  "${sumo_imgui_source_SOURCE_DIR}/imgui.cpp"
  "${sumo_imgui_source_SOURCE_DIR}/imgui_draw.cpp"
  "${sumo_imgui_source_SOURCE_DIR}/imgui_tables.cpp"
  "${sumo_imgui_source_SOURCE_DIR}/imgui_widgets.cpp"
  "${sumo_imgui_source_SOURCE_DIR}/misc/cpp/imgui_stdlib.cpp"
  "${sumo_imgui_source_SOURCE_DIR}/backends/${SUMO_IMGUI_SDL_BACKEND}"
  "${sumo_imgui_source_SOURCE_DIR}/backends/imgui_impl_opengl3.cpp"
)
add_library(Sumo::ImGui ALIAS sumo_imgui)
target_include_directories(sumo_imgui SYSTEM PUBLIC
  "${sumo_imgui_source_SOURCE_DIR}"
  "${sumo_imgui_source_SOURCE_DIR}/backends"
  "${sumo_imgui_source_SOURCE_DIR}/misc/cpp"
)
target_link_libraries(sumo_imgui PUBLIC Sumo::SDL)
target_compile_features(sumo_imgui PUBLIC cxx_std_17)

FetchContent_Declare(sumo_glad_source
  GIT_REPOSITORY https://github.com/Dav1dde/glad.git
  GIT_TAG 73db193f853e2ee079bf3ca8a64aa2eaf6459043
  GIT_SHALLOW FALSE
  GIT_PROGRESS TRUE
  SOURCE_SUBDIR cmake
)
FetchContent_MakeAvailable(sumo_glad_source)

find_package(Python COMPONENTS Interpreter REQUIRED)
execute_process(
  COMMAND "${Python_EXECUTABLE}" -c "import jinja2"
  RESULT_VARIABLE sumo_jinja2_missing
  OUTPUT_QUIET ERROR_QUIET
)
if(NOT sumo_jinja2_missing EQUAL 0)
  message(FATAL_ERROR
    "The OpenGL loader is generated by glad2, which needs Jinja2")
endif()

glad_add_library(sumo_glad STATIC REPRODUCIBLE API gl:core=3.3 EXTENSIONS NONE)
add_library(Sumo::GLAD ALIAS sumo_glad)

set(XM_VERBOSE OFF CACHE BOOL "" FORCE)
set(XM_LINEAR_INTERPOLATION ON CACHE BOOL "" FORCE)
set(XM_RAMPING ON CACHE BOOL "" FORCE)
set(XM_SAMPLE_RATE 0 CACHE STRING "" FORCE)

FetchContent_Declare(sumo_libxm_source
  GIT_REPOSITORY https://github.com/MikeEviscerate/libxm-windows.git
  GIT_TAG 33dcf66028667bc5819001e51d4efa66fedc31d6
  GIT_SHALLOW FALSE
  GIT_PROGRESS TRUE
  SOURCE_SUBDIR src
)
FetchContent_MakeAvailable(sumo_libxm_source)

if(NOT TARGET xm)
  message(FATAL_ERROR "The pinned source did not provide target xm")
endif()

set_target_properties(xm PROPERTIES
  C_STANDARD 17
  C_STANDARD_REQUIRED ON
  C_EXTENSIONS OFF
  INTERPROCEDURAL_OPTIMIZATION OFF
)
if(TARGET xm_common)
  target_compile_options(xm_common INTERFACE
    ${SUMO_STRICT_FP_COMPILE_OPTIONS})
endif()

add_library(sumo_xm INTERFACE)
add_library(Sumo::XM ALIAS sumo_xm)
target_link_libraries(sumo_xm INTERFACE xm)
